// Items
let units = {
	list: {
		"worker": {
			iname: "Казах",
			description: "Хороший казах всегда пригодится",
			name: "worker",
			src: "images/worker.png",
			hitPoints: 80,
			width: 16,
			height: 24,
			gridWidth: 1,
			gridHeight: 1.5,
			damage: [5, 7],
			defense: 1,
			radiuse: 10,
			speed: 1.5,
			sight: 32,
			level: 1,
			maxLevel: 1,
			experiense: 0,
			maxExperiense: 0,
			cost: {"gold": 50},
			frames: [],
		},
		"soldier": {
			iname: "Кремлебот",
			description: "Призовите толпы кремлеботов для спама своих врагов",
			name: "soldier",
			src: "images/soldier.png",
			hitPoints: 160,
			width: 20,
			height: 24,
			gridWidth: 1.25,
			gridHeight: 1.5,
			damage: [11, 15],
			defense: 3,
			radiuse: 15,
			speed: 2,
			sight: 32,
			level: 1,
			maxLevel: 3,
			experiense: 0,
			maxExperiense: 500,
			cost: {"gold": 80, "metal": 10},
			frames: [],
		},
		"meet": {
			iname: "Мясо",
			description: "Специально выращиваемые империей организмы на основе человеческих тел для самоубийственных нападений на врага. Некогда были людьми, но после прихождения в негодность стали материалом для экспериментов и переработки. Отлично держат урон, но сами его нанести почти неспособны. Лучшая защита, вы же для этого их нанимаете?"
		},
	},
	defaults: {
		type: "unit",
		animationIndex: 0,
		direction: 0,
		move: {},
		target: null,
		action: "stand",
		repulsionSpeed: 2,
		selected: false,
		selectable: true,
		directions: 8,
	},
};

// Items
let buildings = {
	list: {
		"capitol": {
			iname: "Капитолий",
			description: "Здание для производства казахов и кремлеботов",
			name: "capitol",
			src: "images/capitol.png",
			hitPoints: 5000,
			width: 48,
			height: 48,
			gridWidth: 3,
			gridHeight: 3,
			damage: [0, 0],
			defense: 10,
			radiuse: 30,
			sight: 48,
			cost: {"gold": 325, "tree": 120, "metal": 80},
			frames: [],
		},
		"temple": {
			iname: "Храм",
			description: "Храм в котором вы можете призывать и воскрешать своих героев",
			name: "temple",
			src: "images/temple.png",
			hitPoints: 3000,
			width: 32,
			height: 48,
			gridWidth: 2,
			gridHeight: 3,
			damage: [0,0],
			defense: 5,
			radiuse: 20,
			sight: 48,
			cost: {"gold": 180, "tree": 60, "metal": 40},
			frames: [],
		},
	},
	defaults: {
		type: "building",
		animationIndex: 0,
		direction: 0,
		speed: 0,
		action: "stand",
		selected: false,
		selectable: true,
		repulsionSpeed: 0,
		directions: 8,
	},
};

// Items
let heroes = {
	list: {
		"leonid": {
			iname: "Леонид",
			description: "Король людей, король Зверей!",
			name: "leonid",
			src: "images/hero.png",
			hitPoints: 500,
			width: 16,
			height: 24,
			gridWidth: 1,
			gridHeight: 1.5,
			damage: [20, 25],
			defense: 4,
			radiuse: 10,
			speed: 2.5,
			sight: 32,
			level: 1,
			maxLevel: 10,
			experiense: 0,
			maxExperiense: 5400,
			cost: {"gold": 165},
			frames: [],
		},
	},
	defaults: {
		type: "hero",
		animationIndex: 0,
		direction: 0,
		move: {},
		action: "stand",
		repulsionSpeed: 2,
		selected: false,
		selectable: true,
		directions: 8,
	},
};

// Miscs
let resources = {
	list: {
		"tree": {
			iname: "Дерево",
			name: "tree",
			src: "images/tree.png",
			width: 16,
			height: 32,
			gridWidth: 1,
			gridHeight: 2,
			mining: 10,
			minerals: 100,
		},
		"goldmine": {
			iname: "Золотая жила",
			name: "goldmine",
			src: "images/goldmine.png",
			width: 32,
			height: 32,
			gridWidth: 2,
			gridHeight: 2,
			mining: 10,
			minerals: 10000,
		},
		"metalcore": {
			iname: "Металлическая жила",
			name: "metalcore",
			src: "images/metalcore.png",
			width: 32,
			height: 32,
			gridWidth: 2,
			gridHeight: 2,
			mining: 10,
			minerals: 1000,
		}
	},
	defaults: {
		type: "resources",
		mining: true,
		mined: false,
		action: "stand",
	},
};